### ISSUE TITLE
Error when snippet includes ]

### ISSUE THREAD

**Issue by pianohacker** [quangnguyen30192/cmp-nvim-ultisnips#31]
The default ultisnips for Rust have a snippet `attr` that contains a `]`.

This breaks the string escaping in https://github.com/quangnguyen30192/cmp-nvim-ultisnips/blob/main/autoload/cmp_nvim_ultisnips.vim#L29 with the following error:

```
Error detected while processing TextChangedI Autocommands for "*":
E5108: Error executing lua Vim(return):Error invoking 'python_execute' on channel 3 (python3-s
cript-host):
Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "/usr/local/lib/python3.9/dist-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pynvim/msgpack_rpc/session.py", line 104, in re
quest
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim(lua):E5107: Error loading lua [string ":lua"]:1: unexpected s
ymbol near ']'
```

**Comment by quangnguyen30192** [comment]
Thanks for reporting, @smjonas  could you have a look?

**Comment by pianohacker** [comment]
I have a PR that fixes my immediate problem. Not sure how it affects snippets in general.

**Comment by smjonas** [comment]
Thank you @pianohacker for reporting. I didn't know pyxeval existed so I kind of used a hacky way to escape the snippets. Please create a PR :)

**Comment by quangnguyen30192** [comment]
@pianohacker  just created a PR already

**Comment by smjonas** [comment]
Oh I just saw it, it looks good!
