### ISSUE TITLE
tab completion does not work anymore

### ISSUE THREAD

**Issue by leonardobanchi** [quangnguyen30192/cmp-nvim-ultisnips#99]
I'm using this plugin with latex using the default lua configuration. Pressing fig<TAB> used to fill the document with a figure environment. After the latest upgrades, now pressing fig<TAB> results in fig<Plug>(cmpu-expand) while fig<CR> produces the old behavior.  Am I doing something wrong of something changed in the latest commits?

**Comment by quangnguyen30192** [comment]
Thanks for reaching out, I just try again and it works fine. 
if you suspect that the cause is from some of recent commits. Could you please check one or two commits back to see which commit causes the issue?

**Comment by akail** [comment]
I hit this issue and started going back through the commits to see where the problem arose.

Looks like the issue started with commit https://github.com/quangnguyen30192/cmp-nvim-ultisnips/commit/f5c5cd6da094ef04a7d6e0bea73f71dfa5dde9bf.

My lua is not very strong so I can't tell what exactly would cause the issue here.

By going to that commit, I do get some more errors though:

```
Error detected while processing TextChangedI Autocommands for "*":
Error executing lua callback: TextChangedI Autocommands for "*"..function provider#python3#Call, line 1: Vim(return):E5108: Error executing lua Vim:Error invoking 'python_eva
l' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/akail/.local/share/nvim/lazy/cmp-nvim-ultisnips/python3/ultisnips_utils.py", line 14, in fetch_current_snippets
    snippets = UltiSnips_Manager._snips(before_line, True)
                                        ^^^^^^^^^^^
NameError: name 'before_line' is not defined
```

, but that may be addressed later due to a refactor it seems

**Comment by leonardobanchi** [comment]
I can confirm this indeed, going back to #24bca5c Tab works as it used to be. In #f5c5cd6 I get the errors mentioned above while in #be2c928 I get no errors but Tab completion stops working. 

So something between #24bca5c and  #be2c928 might have caused this issue. 

Just for reference, here is my conf (just taken from the readme)
```
      ["<Tab>"] = cmp.mapping(
          function(fallback)
            cmp_ultisnips_mappings.expand_or_jump_forwards(fallback)
          end,
          { "i", "s", --[[ "c" (to enable the mapping in command mode) ]] }
       ),
```

**Comment by quangnguyen30192** [comment]
@akail I believe the issue was fixed in https://github.com/quangnguyen30192/cmp-nvim-ultisnips/commit/be2c9281a8b88d33c12306ef1a4b4623e9a3dbee, could you please clean and install the plugin again to make sure you're using the latest version?

**Comment by quangnguyen30192** [comment]
@leonardobanchi   please clean and install the plugin again to make sure you're using the latest version

**Comment by quangnguyen30192** [comment]
@leonardobanchi  the issue you got `fig<TAB> results in fig<Plug>(cmpu-expand) while fig<CR> produces the old behavior`

I'am still investigating. For the workaround, you may update your tab behavior a bit to achieve the old behavior
```
local is_cmp_loaded, cmp = pcall(require, "cmp")
local mappings = require("cmp_nvim_ultisnips.mappings")

...
    ["<Tab>"] = cmp.mapping(function(fallback)
      if cmp.visible() and cmp.get_selected_entry() == nil then
        cmp.select_next_item()
        cmp.confirm({ select = false, cmp.ConfirmBehavior.Insert })
      else
        mappings.expand_or_jump_forwards(fallback)
      end
    end, { "i", "s" }),
...
```

This behavior is to auto select the first selection if no selection selected

**Comment by quangnguyen30192** [comment]
@leonardobanchi the issue of `fig<TAB> results in fig<Plug>(cmpu-expand) while fig<CR> produces the old behavior` has been fixed, please update the plugin to latest version and try it again. Let me know if you have any issues.

**Comment by leonardobanchi** [comment]
many thanks, I can confirm that everything works as expected in the latest version.

**Comment by leonardobanchi** [comment]
many thanks, I can confirm that everything works as expected in the latest version.

**Comment by akail** [comment]
I can also confirm it works.  Thank you!

**Comment by quangnguyen30192** [comment]
thanks for your patient. have fun with it.
